# Generated by Django 5.0.6 on 2024-05-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_upload',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/'),
        ),
    ]
