# Generated by Django 5.0.6 on 2024-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_upload',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
